@token = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcnNoLndlYm9zbW90aWNAZ21haWwuY29tIiwiaWQiOiI2NGRkYTcxMWY2ZDRjZWVhYTI5NWM2M2IiLCJpYXQiOjE2OTIyNTQ0MjAsImV4cCI6MTY5MjI1ODAyMCwiYXVkIjoiNjRkZGE3MTFmNmQ0Y2VlYWEyOTVjNjNiIiwiaXNzIjoiYWJjLmNvbSJ9.rQfPJ1KlPF_fF4Z3oshdrAFrgA3UTU4J2yJHXz3ecwo
@url = http://localhost:3000/

####
GET {{url}}
Content-Type: application/json
Authorization: {{token}}

### Register
POST {{url}}auth/register
Content-Type: application/json

{
    "email": "sss@gmail.com",
    "password": "abc@12"
}

### Login
POST {{url}}auth/login
Content-Type: application/json

{
    "email": "harsh@gmail.com",
    "password": "abc@12"
}

### Refresh-token
POST {{url}}auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNzc0BnbWFpbC5jb20iLCJpZCI6IjY0ZDllOTEzYjc3M2FkMzczMjc4NDRjMiIsImlhdCI6MTY5MjAxNTc2NSwiZXhwIjoxNzIzNTczMzY1LCJhdWQiOiI2NGQ5ZTkxM2I3NzNhZDM3MzI3ODQ0YzIiLCJpc3MiOiJhYmMuY29tIn0.kN3nnHouZrXvbiywZbJH1-wFU-n_IS7D2x9OfbzEmOU"
}

### Logout
DELETE {{url}}auth/logout
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcnNoQGdtYWlsLmNvbSIsImlkIjoiNjRkYzc1ZjJhNjViYTIzYTZmZDgxNzY2IiwiaWF0IjoxNjkyMTc2NjcyLCJleHAiOjE3MjM3MzQyNzIsImF1ZCI6IjY0ZGM3NWYyYTY1YmEyM2E2ZmQ4MTc2NiIsImlzcyI6ImFiYy5jb20ifQ.I7WcXUpCKw2FW5jP4duEPoEWJWkqfoj0ROVwOgJKWKM"
}

### Add Company
POST {{url}}company
Content-Type: application/json
Authorization: {{token}}

{
    "name": "WebOsmotic",
    "email": "harsh.webosmotic@gmail.com",
    "address": {
        "line1": "A-6. someshwar nagar society",
        "line2": "opp. Joggers Park Road",
        "city": "Surat",
        "state": "Gujarat",
        "country": "India",
        "zipCode": "395007"
    },
    "contact": "8460618624",
    "status": "ACTIVE"
}

### Get Companies
GET {{url}}company
Authorization: {{token}}

### Get Company by ID
GET {{url}}company/64dca8601ef93395a0b2ed3e
Authorization: {{token}}

### Update Company
PUT {{url}}company/64dca8601ef93395a0b2ed3e
Content-Type: application/json
Authorization: {{token}}

{
    "name": "WebOsmotic",
    "email": "harsh.webosmotic@gmail.com",
    "address": {
        "line1": "A-6. someshwar nagar society",
        "line2": "opp. Joggers Park Road",
        "city": "Surat",
        "state": "Gujarat",
        "country": "India",
        "zipCode": "395007"
    },
    "contact": "8460618624",
    "status": "ACTIVE"
}

### Delete Company by ID
DELETE {{url}}company/64dca8601ef93395a0b2ed3e
Authorization: {{token}}


### Update Status by ID
PATCH {{url}}company/64dc9f6c21946a4089b9745b
Content-Type: application/json
Authorization: {{token}}

{
    "status": "INACTIVE"
}


################################################### Employee Collection #########################################################

### Add Employee
POST {{url}}api/employee/register
Content-Type: application/json

{
    "email": "shailesh.webosmotic@gmail.com",
    "password": "abc",
    "firstName": "Shailesh",
    "lastName": "Umaraliya",
    "designation": "DEVELOPER"
}

### Get Emmployee List
GET {{url}}api/employee
Content-Type: application/json

### Update employeee
PUT {{url}}api/employee/64dda84b7d9db49c3d71ef9c
Content-Type: application/json

{
    "email": "shailesh.webosmotic@gmail.com",
    "firstName": "Shailesh",
    "lastName": "Umaraliya",
    "designation": "TEAM_LEADER"
}

### Delete Emmployee
DELETE {{url}}api/employee/64dda9a92ac05e4a9020955b
Content-Type: application/json

### Set CompanyId
PATCH  {{url}}api/employee/64dda711f6d4ceeaa295c63b
Content-Type: application/json

{
    "companyId": "64dc9f6c21946a4089b9745b"
}