@token = bearer TOKEN

@refreshToken = TOKEN

@url = http://localhost:3000/api/

################################################### Normal Auth Collection #########################################################

###
GET {{url}}
Content-Type: application/json
Authorization: {{token}}

### Register
POST {{url}}auth/register
Content-Type: application/json

{
    "email": "sss@gmail.com",
    "password": "abc@12"
}

### Login
POST {{url}}auth/login
Content-Type: application/json

{
    "email": "harsh@gmail.com",
    "password": "abc@12"
}

### Refresh-token
POST {{url}}auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "{{refreshToken}}"
}

### Logout
DELETE {{url}}auth/logout
Content-Type: application/json

{
    "refreshToken" : "{{refreshToken}}"
}

################################################### Company Collection #########################################################

### Add Company
POST {{url}}company
Content-Type: application/json
Authorization: {{token}}

{
    "name": "WebOsmotic",
    "email": "harsh.webosmotic@gmail.com",
    "address": {
        "line1": "A-6. someshwar nagar society",
        "line2": "opp. Joggers Park Road",
        "city": "Surat",
        "state": "Gujarat",
        "country": "India",
        "zipCode": "395007"
    },
    "contact": "8460618624",
    "status": "ACTIVE"
}

### Get Companies
GET {{url}}company
Authorization: {{token}}

### Get Company by ID
GET {{url}}company/64dca8601ef93395a0b2ed3e
Authorization: {{token}}

### Update Company
PUT {{url}}company/64dca8601ef93395a0b2ed3e
Content-Type: application/json
Authorization: {{token}}

{
    "name": "WebOsmotic",
    "email": "harsh.webosmotic@gmail.com",
    "address": {
        "line1": "A-6. someshwar nagar society",
        "line2": "opp. Joggers Park Road",
        "city": "Surat",
        "state": "Gujarat",
        "country": "India",
        "zipCode": "395007"
    },
    "contact": "8460618624",
    "status": "ACTIVE"
}

### Delete Company by ID
DELETE {{url}}company/64dca8601ef93395a0b2ed3e
Authorization: {{token}}


### Update Status by ID
PATCH {{url}}company/64dc9f6c21946a4089b9745b
Content-Type: application/json
Authorization: {{token}}

{
    "status": "INACTIVE"
}


################################################### Employee Collection #########################################################

### Add Employee
POST {{url}}employee/register
Content-Type: application/json

{
    "email": "shailesh.webosmotic@gmail.com",
    "password": "abc",
    "firstName": "Shailesh",
    "lastName": "Umaraliya",
    "designation": "DEVELOPER"
}

### Get Emmployee List
GET {{url}}employee
Content-Type: application/json

### Account Verify
GET {{url}}employee/account-verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYWlsZXNoLndlYm9zbW90aWNAZ21haWwuY29tIiwiaWQiOiI2NGRkYjdkZWY1OTk4ZDBkODRkMmViNTciLCJpYXQiOjE2OTIzMzM5ODAsImV4cCI6MTY5MjMzNzU4MH0.DkCqltG_wvBGDho9SNlRzGoV90uEVhQ2MSk83Ka2HtM

### Login Employee
POST {{url}}employee/login
Content-Type: application/json

{
    "email": "abc.webosmotic@gmail.com",
    "password": "abc"
}

### Refresh token
POST {{url}}employee/refresh-token
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

### Logout 
DELETE {{url}}employee/logout
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

### Get Employee 
GET {{url}}employee?search=ABC&designation=DEVELOPER
Content-Type: application/json
Authorization: {{token}}

### Get Employee by ID
GET {{url}}employee/64ddb813f5998d0d84d2eb5b
Content-Type: application/json
Authorization: {{token}}

### Update employeee
PUT {{url}}employee/64ddb813f5998d0d84d2eb5b
Content-Type: application/json
Authorization: {{token}}

{
    "email": "shailesh.webosmotic@gmail.com",
    "firstName": "Shailesh",
    "lastName": "Umaraliya",
    "designation": "TEAM_LEADER"
}

### Delete Emmployee
DELETE {{url}}employee/64dda9a92ac05e4a9020955b
Content-Type: application/json

### Set CompanyId
PATCH  {{url}}employee/64dda711f6d4ceeaa295c63b
Content-Type: application/json

{
    "companyId": "64dc9f6c21946a4089b9745b"
}